/**
 * This file is part of Hercules.
 * http://herc.ws - http://github.com/HerculesWS/Hercules
 *
 * Copyright (C) 2012-2025 Hercules Dev Team
 *
 * Hercules is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef COMMON_PACKETS_LEN_H
#define COMMON_PACKETS_LEN_H

#if defined(PACKETVER_ZERO)
#include "common/packets/packets_len_zero.h"
#elif defined(PACKETVER_RE)
#include "common/packets/packets_len_re.h"
#elif defined(PACKETVER_SAK)
#include "common/packets/packets_len_sak.h"
#elif defined(PACKETVER_AD)
#include "common/packets/packets_len_ad.h"
#else
#include "common/packets/packets_len_main.h"
#endif

// Korangar fork additions. Declared HERE, not in common/packets/packets<year>_len_*.h,
// because those files are autogenerated and carry a "do not commit manual changes"
// banner — a regeneration would silently drop the entry, and a client packet with
// no length entry makes clif_parse *disconnect the session* rather than warn.
// Keep every id within [MIN_PACKET_DB, MAX_PACKET_DB] (0x0064..0x0F00); anything
// outside is rejected by packets_addLen's assert and packetdb_addpacket.
//
// 0x0F00 CZ_CANCEL_CAST — abort the caster's own in-progress cast. No payload, so
// 2 bytes (header only). See clif_parse_CancelCast.
packetLen(0x0f00, 2)

// 0x0EFF ZC_PARTY_INVITE_SENDER — companion to ZC_PARTY_JOIN_REQ carrying the
// inviter's character name, which the official packet does not include.
// 2 (header) + 4 (party id) + 24 (NAME_LENGTH) = 30. See clif_party_invite.
packetLen(0x0eff, 30)

// 0x0EFE ZC_SKILL_FAIL_REASON — companion to ZC_ACK_TOUSESKILL naming the runtime
// outcome behind a cause-0 failure, which the official cause enum has no code for.
// 2 (header) + 2 (skill id) + 2 (reason) = 6. See clif_skill_fail_reason.
packetLen(0x0efe, 6)

#endif /* COMMON_PACKETS_LEN_H */
